name: Continous Integration

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Prettier Check
        run: npx prettier . --check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
